Repository GSG-G11/Braa-Ayman-API-project, pull requests merged in 2022-02, with the labels that each got.

#2 create files
  index.html
  main.js
  style.css
Labels: Awaiting Review, Done

#4 add search bar to the bage
  .vscode/settings.json
  index.html
  style.css
Labels: Done

#7 add function fetch To bring XML
  main.js
Labels: Awaiting Review, Done

#9 6 create the anime card
  anime.jpg
  index.html
  style.css
Labels: Done

#10 add function and event to js file to store data
  index.html
  main.js
Labels: Awaiting Review

#12 update files
  index.html
  style.css
Labels: Done

#14 add main addition
  index.html
  main.js
Labels: Done

#17 add final api
  main.js
Labels: Done

#20 add image and title from api to anime card
  index.html
  main.js
Labels: Done

#22 remove old cards when new search
  main.js
Labels: Done

#24 update files
  index.html
  main.js
  style.css
Labels: Done

#26 fix style
  main.js
  style.css
Labels: Done

#28 gallery button dom
  index.html
  main.js
Labels: Done

#30 add gif
  index.html
  main.js
Labels: Done

#32 fixed
  index.html
  main.js
  style.css
Labels: Done

#34 remove anime details
  index.html
  main.js
Labels: Done

#36 35 fixed
  index.html
  main.js
Labels: Awaiting Review

#38 show message not found when the user enter fack name
  index.html
  main.js
  style.css
Labels: Done

#40 fix style
  home.css
  home.html
  index.html
  style.css
Labels: Done

#44 Make-header-responsive
  home.css
  index.html
  style.css
Labels: Done

#46 updata main.js
  main.js
Labels: Awaiting Review

#48 fixed code
  index.html
  main.js
  style.css
Labels: Done

#50 add font and animation
  style.css
Labels: Done

#52 updata home.html
  home.css
  home.html
  index.html
  style.css
Labels: Awaiting Review

#54 add img
  avatar.png
Labels: Done

#55 edit gallery Dom
  index.html
  main.js
Labels: Done

#57 fix style
  home.css
  style.css
Labels: Done

#59 create folders
  css/home.css
  css/style.css
  home.html
  imgs/anime.jpg
  imgs/avatar.png
  index.html
  js/main.js
Labels: Done

#63 Fix problems
  home.html
  index.html
Labels: Done

#67 fixed code
  home.html
  index.html
  js/main.js
Labels: Done

#71 fix
  css/style.css
Labels: Done
